#Jekyll configuration
name: Saw Steven
title: The Future of Medical Genetics and the Importance of Digital Health
description: GBAC Blog post - Steven 
url: "https://PokieSteven.github.io/Blog1/"
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
