#Jekyll configuration
name: Saw Steven
description: 
url: "https://PokieSteven.github.io/The-Future-of-Medical-Genetics-and-the-Importance-of-Digital-Health/"
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
